### ISSUE TITLE
Facing Error while running module with docxtemplater version 3.32.3

### ISSUE THREAD

**Issue by RajatBhardwaj007** [evilc0des/docxtemplater-image-module-free#10]
Hi,
I was running docxtemplater version 3.14.5 with the image module and was working fine. Recently due to a requirement for including angular-parser(https://docxtemplater.com/docs/angular-parse/), which requires a docxtemplater version > 3.32.3, I upgraded my docxtemplater version. Now, while using image module I am facing below error:

`"Cannot read properties of undefined (reading 'part'): TypeError: Cannot read properties of undefined (reading 'part')\n    at ScopeManager._getValue (/usr/src/app/backend/node_modules/docxtemplater/js/scope-manager.js:48:36)\n    at ScopeManager.getValue (/usr/src/app/backend/node_modules/docxtemplater/js/scope-manager.js:167:30)\n    at ImageModule.render (/usr/src/app/backend/node_modules/open-docxtemplater-image-module/js/index.js:125:40)\n    at moduleRender (/usr/src/app/backend/node_modules/docxtemplater/js/render.js:9:30)\n    at /usr/src/app/backend/node_modules/docxtemplater/js/render.js:26:26\n    at Array.map (<anonymous>)\n    at render (/usr/src/app/backend/node_modules/docxtemplater/js/render.js:24:24)\n    at XmlTemplater.render (/usr/src/app/backend/node_modules/docxtemplater/js/xml-templater.js:199:22)\n    at /usr/src/app/backend/node_modules/docxtemplater/js/docxtemplater.js:425:21\n    at Array.forEach (<anonymous>)\n    at Docxtemplater.render (/usr/src/app/backend/node_modules/docxtemplater/js/docxtemplater.js:419:32)`

Rest assured, all code for using image module is same, just that I have upgraded version of docxtemplater tp 3.32.3

Any help would be appreciated. Thanks.

**Comment by heyline** [comment]
can you provide an example of how to use this module in angular, thanks
